// Generated by tools/generate_protocol.mjs from protocol/schema.json.

export const SYNC_BYTES = [0x4c, 0x5a] as const;
export const VERSION = 1;
export const MAX_PAYLOAD = 1024;
export const HEADER_SIZE = 8;

export enum MessageType {
  Hello = 1,
  HelloAck = 2,
  Text = 3,
  Error = 4,
  Disconnect = 5,
  SessionStart = 6,
  PromptChunk = 7,
  PromptEnd = 8,
  AssistantChunk = 9,
  ExecRequest = 10,
  ExecResultChunk = 11,
  ExecResultEnd = 12,
  Complete = 13,
  Cancel = 14,
  NewSession = 15,
  SessionReady = 16,
  Ping = 17,
  Pong = 18,
  ReadFileRequest = 19,
  ReadFileChunk = 20,
  ReadFileEnd = 21,
  WriteFileStart = 22,
  WriteFileChunk = 23,
  WriteFileEnd = 24,
  WriteFileResult = 25,
  ListFilesRequest = 26,
  ListFilesChunk = 27,
  ListFilesEnd = 28,
  StyledAssistantChunk = 29,
  ToolStatus = 30,
}

export enum ClientMode {
  OneShot = 1,
  Interactive = 2,
}
