import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const COLORS = new Map(Object.entries({
  black: 0, blue: 1, green: 2, cyan: 3, red: 4, magenta: 5, brown: 6,
  lightgray: 7, darkgray: 8, lightblue: 9, lightgreen: 10, lightcyan: 11,
  lightred: 12, lightmagenta: 13, yellow: 14, lightyellow: 14, white: 15,
}));

const ROLES = ["text", "title", "accent", "status", "ok", "error"];

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const config = JSON.parse(await readFile(path.join(root, "config", "themes.json"), "utf8"));
const themes = validate(config);
const output = path.join(root, "dos", "themes_gen.h");
const content = renderC(themes);

if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8").catch(() => "") !== content) {
    console.error(`${path.relative(root, output)} is stale; run npm run themes:generate`);
    process.exitCode = 1;
  }
} else {
  await writeFile(output, content, "utf8");
}

function validate(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("themes.json must contain an object");
  }
  const entries = Object.entries(value.themes ?? {});
  if (entries.length === 0) throw new Error("themes must not be empty");
  if (entries[0][0] !== "default") throw new Error("the first theme must be \"default\"");
  const names = new Set();
  return entries.map(([name, theme]) => {
    if (!/^[a-z][a-z0-9]{0,14}$/.test(name)) {
      throw new Error(`invalid theme name: ${name}`);
    }
    if (names.has(name)) throw new Error(`duplicate theme name: ${name}`);
    names.add(name);
    if (typeof theme !== "object" || theme === null || Array.isArray(theme)) {
      throw new Error(`theme ${name} must be an object`);
    }
    const keys = Object.keys(theme);
    for (const key of keys) {
      if (key !== "background" && !ROLES.includes(key)) {
        throw new Error(`theme ${name} has unknown role: ${key}`);
      }
    }
    for (const key of ["background", ...ROLES]) {
      if (theme[key] === undefined) throw new Error(`theme ${name} is missing role: ${key}`);
    }
    const background = color(name, "background", theme.background);
    const roleAttributes = {};
    for (const role of ROLES) {
      const [foreground, roleBackground] = String(theme[role]).split("@");
      const fg = color(name, role, foreground);
      const bg = roleBackground === undefined ? background : color(name, `${role} background`, roleBackground);
      roleAttributes[role] = (bg << 4) | fg;
    }
    return { name, background, roles: roleAttributes };
  });
}

function color(theme, role, name) {
  const value = COLORS.get(name);
  if (value === undefined) {
    throw new Error(`theme ${theme} role ${role}: unknown color "${name}"`);
  }
  return value;
}

function renderC(themes) {
  const rows = themes.map((theme) => {
    const attributes = ROLES.map((role) => hex(theme.roles[role])).join(", ");
    return `    { "${theme.name}", ${attributes} },`;
  }).join("\n");
  return `/* Generated by tools/generate_themes.mjs from config/themes.json. */
#ifndef LIZA_THEMES_GEN_H
#define LIZA_THEMES_GEN_H

typedef struct {
    const char *name;
    unsigned char text;
    unsigned char title;
    unsigned char accent;
    unsigned char status;
    unsigned char ok;
    unsigned char error;
} liza_theme;

#define LIZA_THEME_DEFAULT 0
#define LIZA_THEME_COUNT ${themes.length}

static const liza_theme liza_themes[LIZA_THEME_COUNT] = {
${rows}
};

#endif
`;
}

function hex(value) {
  return `0x${value.toString(16).padStart(2, "0")}`;
}
