import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const schema = JSON.parse(await readFile(path.join(root, "protocol", "schema.json"), "utf8"));
const outputs = new Map([
  [path.join(root, "host", "protocol.generated.ts"), renderTypeScript(schema)],
  [path.join(root, "dos", "proto_gen.h"), renderC(schema)],
]);

if (process.argv.includes("--check")) {
  let stale = false;
  for (const [file, content] of outputs) {
    if (await readFile(file, "utf8").catch(() => "") !== content) {
      console.error(`${path.relative(root, file)} is stale; run npm run protocol:generate`);
      stale = true;
    }
  }
  if (stale) process.exitCode = 1;
} else {
  for (const [file, content] of outputs) await writeFile(file, content, "utf8");
}

function renderTypeScript(value) {
  const messages = value.messages.map((message) => `  ${pascalCase(message.name)} = ${message.value},`).join("\n");
  const modes = value.modes.map((mode) => `  ${pascalCase(mode.name)} = ${mode.value},`).join("\n");
  return `// Generated by tools/generate_protocol.mjs from protocol/schema.json.\n\nexport const SYNC_BYTES = [${value.sync.map(hex).join(", ")}] as const;\nexport const VERSION = ${value.version};\nexport const MAX_PAYLOAD = ${value.maxPayload};\nexport const HEADER_SIZE = ${value.headerSize};\n\nexport enum MessageType {\n${messages}\n}\n\nexport enum ClientMode {\n${modes}\n}\n`;
}

function renderC(value) {
  const messages = value.messages.map((message) => `#define LIZA_${message.name} ${message.value}`).join("\n");
  const modes = value.modes.map((mode) => `#define LIZA_MODE_${mode.name} ${mode.value}`).join("\n");
  return `/* Generated by tools/generate_protocol.mjs from protocol/schema.json. */\n#ifndef LIZA_PROTO_GEN_H\n#define LIZA_PROTO_GEN_H\n\n#define LIZA_SYNC_0 ${hex(value.sync[0])}\n#define LIZA_SYNC_1 ${hex(value.sync[1])}\n#define LIZA_VERSION ${value.version}\n#define LIZA_MAX_PAYLOAD ${value.maxPayload}\n#define LIZA_HEADER_SIZE ${value.headerSize}\n\n${messages}\n\n${modes}\n\n#endif\n`;
}

function pascalCase(name) {
  return name.toLowerCase().replace(/(^|_)([a-z0-9])/g, (_match, _separator, letter) => letter.toUpperCase());
}

function hex(value) {
  return `0x${value.toString(16).padStart(2, "0")}`;
}
